// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef KACCOUNTS_VERSION_H
#define KACCOUNTS_VERSION_H

#define KACCOUNTS_VERSION_STRING "21.12.0"
#define KACCOUNTS_VERSION_MAJOR 21
#define KACCOUNTS_VERSION_MINOR 12
#define KACCOUNTS_VERSION_PATCH 0
#define KACCOUNTS_VERSION ((21<<16)|(12<<8)|(0))

#endif
