CC=gcc
all: hellofriend cookie pyrymadcalc tom triangle

hellofriend: ../hellofriend/hello.c
	$(CC) -g ../hellofriend/hello.c -o ../bin/hellofriend -lm
cookie: ../my_god_its_sheple_sharing_cookies/cookie.c
	$(CC) -g ../my_god_its_sheple_sharing_cookies/cookie.c -o ../bin/cookie -lm
pyrymadcalc: ../Pyrymad_calc_thing_uh/Pyrymad_calc.c
	$(CC) -g ../Pyrymad_calc_thing_uh/Pyrymad_calc.c -o ../bin/Pyrymad_calc -lm
tom: ../tom/tom.c
	$(CC) -g ../tom/tom.c -o ../bin/tom -lm
triangle: ../triangle/triangle.c
	$(CC) -g ../triangle/triangle.c -o ../bin/triangle -lm