// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef KARCHIVE_VERSION_H
#define KARCHIVE_VERSION_H

#define KARCHIVE_VERSION_STRING "5.89.0"
#define KARCHIVE_VERSION_MAJOR 5
#define KARCHIVE_VERSION_MINOR 89
#define KARCHIVE_VERSION_PATCH 0
#define KARCHIVE_VERSION ((5<<16)|(89<<8)|(0))

#endif
