// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef KDNSSD_VERSION_H
#define KDNSSD_VERSION_H

#define KDNSSD_VERSION_STRING "5.89.0"
#define KDNSSD_VERSION_MAJOR 5
#define KDNSSD_VERSION_MINOR 89
#define KDNSSD_VERSION_PATCH 0
#define KDNSSD_VERSION ((5<<16)|(89<<8)|(0))

#endif
