// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef KSCREEN_VERSION_H
#define KSCREEN_VERSION_H

#define KSCREEN_VERSION_STRING "5.23.4"
#define KSCREEN_VERSION_MAJOR 5
#define KSCREEN_VERSION_MINOR 23
#define KSCREEN_VERSION_PATCH 4
#define KSCREEN_VERSION ((5<<16)|(23<<8)|(4))

#endif
