// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef KWAYLAND_VERSION_H
#define KWAYLAND_VERSION_H

#define KWAYLAND_VERSION_STRING "5.89.0"
#define KWAYLAND_VERSION_MAJOR 5
#define KWAYLAND_VERSION_MINOR 89
#define KWAYLAND_VERSION_PATCH 0
#define KWAYLAND_VERSION ((5<<16)|(89<<8)|(0))

#endif
