// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef KXMLGUI_VERSION_H
#define KXMLGUI_VERSION_H

#define KXMLGUI_VERSION_STRING "5.89.0"
#define KXMLGUI_VERSION_MAJOR 5
#define KXMLGUI_VERSION_MINOR 89
#define KXMLGUI_VERSION_PATCH 0
#define KXMLGUI_VERSION ((5<<16)|(89<<8)|(0))

#endif
