// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef SONNET_VERSION_H
#define SONNET_VERSION_H

#define SONNET_VERSION_STRING "5.89.0"
#define SONNET_VERSION_MAJOR 5
#define SONNET_VERSION_MINOR 89
#define SONNET_VERSION_PATCH 0
#define SONNET_VERSION ((5<<16)|(89<<8)|(0))

#endif
